# Generated by Django 4.1.7 on 2023-03-11 09:59

from django.db import migrations
import prose.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jiri_one', '0002_alter_post_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_cze',
            field=prose.fields.RichTextField(verbose_name='Post content CZE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_eng',
            field=prose.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Post content ENG'),
        ),
    ]
