exclude = [
    "src/easyblog/migrations",
    "src/jiri_one/migrations",
    "src/utils",
    "src/jiri_one/management",
]

[lint]
# Enable comprehensive rule sets
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "PIE", # flake8-pie
    "SIM", # flake8-simplify
]

ignore = [
    "E731",  # lambda assignment (keep your preference)
    "E501",  # line too long (let editor handle this)
    "C408",  # dict() calls with keyword arguments
    "N805",  # disable first parameter to be self
]

# Ruff handles formatting and imports
[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.isort]
known-first-party = ["jiri_one", "easyblog"]

[lint.flake8-bugbear]
extend-immutable-calls = ["dict", "frozenset", "set"]
