# Generated by Django 4.1 on 2022-08-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20, verbose_name="Author's nick")),
                ('first_name', models.CharField(max_length=20, verbose_name="Author's firstname")),
                ('last_name', models.CharField(max_length=20, verbose_name="Author's lastname")),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cze', models.CharField(max_length=20, verbose_name='Tag name CZE')),
                ('name_eng', models.CharField(max_length=20, verbose_name='Tag name ENG')),
                ('desc_cze', models.CharField(max_length=100, verbose_name='Tag description CZE')),
                ('desc_eng', models.CharField(max_length=100, verbose_name='Tag description ENG')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cze', models.CharField(max_length=100, verbose_name='Post title CZE')),
                ('title_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post title ENG')),
                ('content_cze', models.TextField(verbose_name='Post content CZE')),
                ('content_eng', models.TextField(blank=True, null=True, verbose_name='Post content ENG')),
                ('url_cze', models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Post URL CZE')),
                ('url_eng', models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Post URL ENG')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Fist release time')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='Last modification time')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jiri_one.author')),
                ('tags', models.ManyToManyField(to='jiri_one.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Comment title')),
                ('content', models.TextField(verbose_name='Comment content')),
                ('nick', models.CharField(max_length=20, verbose_name='Comment author - nick')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiri_one.post')),
            ],
        ),
    ]
