# Generated by Django 4.1 on 2022-08-27 08:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jiri_one.models


class Migration(migrations.Migration):

    dependencies = [
        ('jiri_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='url_cze',
            field=models.SlugField(default=None, editable=False, max_length=25, unique=True, verbose_name='Tag URL CZE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='url_eng',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=25, null=True, verbose_name='Tag URL ENG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jiri_one.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_eng',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Post content ENG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(default=jiri_one.models.Post.get_next_id, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Fist release time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_cze',
            field=models.CharField(max_length=100, unique=True, verbose_name='Post title CZE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_eng',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Post title ENG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_eng',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=100, null=True, unique=True, verbose_name='Post URL ENG'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc_eng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag description ENG'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_cze',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tag name CZE'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_eng',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Tag name ENG'),
        ),
    ]
