# Generated by Django 4.1 on 2022-08-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiri_one', '0002_alter_post_options_alter_tag_options_tag_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jiri_one.post'),
        ),
    ]
