# Generated by Django 4.1 on 2022-08-28 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiri_one', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 28, 18, 3, 59, 715416), verbose_name='Comment time'),
            preserve_default=False,
        ),
    ]
