name: Django Deploy CD
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ secrets.HOST }}
            User ${{ secrets.USERNAME }}
            Port ${{ secrets.PORT }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Check out the source
        run: sshpass -p ${{ secrets.PASSPHRASE }} ssh staging 'cd ${{ secrets.DEST_PATH }} && git fetch && git reset --hard R/main && poetry install --no-root --with production && poetry run python manage.py collectstatic --noinput'

      - name: Restart the gunicorn server
        run: sshpass -p ${{ secrets.PASSPHRASE }} ssh staging 'systemctl --user restart gunicorn_jiri_one.socket'
