name: Django Tests (PyTest)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]
    services:
      db:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install '.[dev]'
      - name: Remove installed easyblog_django
        run: pip uninstall -y easyblog_django
      - name: Run tests
        run: pytest -v
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
